# Generated by Django 3.2.13 on 2022-06-21 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='amra_user',
        ),
    ]
